### ISSUE TITLE
Ignore values from bad API calls so we don't get NaNs showing up

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#105]
![image](https://user-images.githubusercontent.com/4713204/110220762-a38e7980-7e7c-11eb-8a32-336f49478359.png)

**Comment by Klakurka** [comment]
![image](https://user-images.githubusercontent.com/4713204/110221798-0d118680-7e83-11eb-8119-deab09f63df0.png)

**Comment by paOol** [comment]
defaults to 'Send any amount' message when receiving a NaN value

**Comment by Klakurka** [comment]
Just want to double check what happens when bad data comes in when `goalAmount` is set.
