### ISSUE TITLE
Have '#' be optional when specifying colours for the theme

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#107]
The following would then be valid:

`const theme = {
    palette: {
      primary: CB8455,
      secondary: '#E4E4E4',
      tertiary: '333333'
    }
  }`

Perhaps we should still do something if they actually enter garbage? Right now they just get a transparent/white colour which is kinda weird.

**Comment by AaronThomasDev** [comment]
Can I give this a go?
