### ISSUE TITLE
customizable button

### ISSUE THREAD

**Issue by mr-zwets** [PayButton/paybutton#12]
Currently the paybutton is very hard to customize as you have to overwrite all the CSS for the button design.

Ideally a user can design his own button and plugin paybutton without having to overwrite a large number of already existing rules.
A good first step would be the option to pass in a variable to change the color and text of the button.

If there is already a quick method to do this I'd love to hear it.

**Comment by Klakurka** [comment]
Let's make the styling optional (either opt-in or opt-out).

**Comment by Klakurka** [comment]
Done as part of the new release.
