### ISSUE TITLE
rest.bitcoin.com is down

### ISSUE THREAD

**Issue by roovyshapiro** [PayButton/paybutton#126]
I've noticed a lot of errors when the button tries to contact rest.bitcoin.com. It seems that service is permanently down.
Do you plan to migrate services to fullstack.cash? Will this affect the functionality of the button as it is or will donations still continue to work?
Thank you!

https://i.imgur.com/HmigFEK.png
https://i.imgur.com/SWzqQWl.png

From https://rest.bitcoin.com/ :

Dear rest.bitcoin.com developers,
As some of you may have noticed, the free, public rest.bitcoin.com endpoints have at times been unstable due to dramatically increased load from the growing number of products and services using it. In order to continue providing the best developer experience possible, we’re upgrading this free service to run on Fullstack.cash.
This change is effective immediately, so please ensure you update your endpoints to api.fullstack.cash as soon as possible.
Fullstack.cash is free to use for 20 full-node, indexer, and SLPDB requests per minute. For comprehensive plans, please refer to the pricing page.
Please also check rest.bch.actorforth.org for API and slpdb.bch.actorforth.org for SLPDB.

Sincerely,

The Bitcoin.com Team

**Comment by Klakurka** [comment]
Bitcoin.com's API continues to work although is not a great API to rely on since it's been deprecated.

The next major release will switch to use https://github.com/PayButton/paybutton-server which is also open source.
