### ISSUE TITLE
Improve / clean up the way the currency image is applied to the qr code

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#178]
Apparently it's a bit of a mess right now.

**Comment by johnkuney** [comment]
Were there any specific issues with it?
I've been looking through, it seems well structured all things considered... we're using a qrcode package and passing the currency image through the props object...Most convoluted thing I see is the data image is inside a useMemo hook, but that is so the fill color of the svg will update if the theme changes...

**Comment by Klakurka** [comment]
Maybe @ScottMcDermid or @Gattaca1 can clarify as I created this based on their comments while working through the XEC branch.

**Comment by johnkuney** [comment]
Im going to go ahead and close this one as the image handling was tightened up a bit when I added the xec logo
