### ISSUE TITLE
Precision error on amount

### ISSUE THREAD

**Issue by chedieck** [PayButton/paybutton#208]
Suppose the following config:
```
    var config = {
      to: 'bitcoincash:qpfx6l0x85kc5qaah4wx9nahezcgqefnss2sp0cy06',
      amount: 4.5,
      ...
    }
```
I get:
![image](https://github.com/PayButton/paybutton/assets/21281174/5bc54612-4058-4ff5-818d-1ce86d21a052)

and upon reloading:
![image](https://github.com/PayButton/paybutton/assets/21281174/c71a839c-07ad-465a-8828-08f1e7848e88)

...so it is always floating around the precise value which should be `4.5`.

**Comment by Klakurka** [comment]
This isn't a bug. By default (it can be turned off), we add tension satoshis at the end to allow multiple people to pay at once and be able to detect them separately. It's not a perfect solution but it works well at low volume.
