### ISSUE TITLE
Unnecessary redundant fiat currency text

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#267]
Probably better to just go with $ instead of US$ I think.

![image](https://github.com/PayButton/paybutton/assets/4713204/743e660a-2158-4ce8-b472-eefe2fceb162)

Obviously needs to be the same for CAD and any future currencies that are eventually added.

**Comment by johnkuney** [comment]
This looks to be resolved now...

**Comment by Klakurka** [comment]
It's still happening on the CAD side 
<img width="108" alt="image" src="https://github.com/PayButton/paybutton/assets/4713204/b9347ef0-013e-439c-8930-1b7138d029e6">

**Comment by Klakurka** [comment]
Happens on USD too - ecashstaking has this issue.
