### ISSUE TITLE
Widget not re-rendering correctly

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#289]
This is referring to when done va JS (re-rendering the widget).

**Comment by Klakurka** [comment]
Still an issue.

**Comment by johnkuney** [comment]
@chedieck I made a branch in ecash-land that shows this issue happening. https://github.com/BlockchainVentures/ecash-land/tree/widget-amount-update-issue

If you run it, you can see the amount will update on the first pixel click, but not on subsequent clicks. I've also displayed the amount and selected index below the widget to show the prop is being passed and updated properly

The weirdest part though is if you click another address's set of pixels the amount does update...(the grid is split evenly between 5 addresses, so every X amount of pixels there is a different address attributed to the widget, and for some reason if you click between these sets the amount is getting updated) 

Let me know if you have any ideas here. Its possible its an error in this build, or with paybutton or both. Another good test would be to make a super simple react app that uses an amount state on a widget and see if the issue repeatable there
