### ISSUE TITLE
Update website

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#29]
- Setup site with https://www.docz.site/docs/getting-started, with GitHub actions.
- Include donation button that leverages PayButton.
- Include 'generate basic PayButton' form.
- Include docs.
- Include link to github.

**Comment by Klakurka** [comment]
We're going to do the framework setup for this and then the design will be outsourced.

**Comment by Klakurka** [comment]
TODO:

 - Fix proptypes component not working.
 - Fix nav links.
 - Fix viewable-JS not working.
 - Setup proper landing page.

**Comment by Klakurka** [comment]
We're going to try switching from docz to docsify instead.

**Comment by ScottMcDermid** [comment]
- Page offsets occasionally (not reproducible)
- Broken nav/fragment links
- Get Started should have 'What is PayButton?' and 'Basic Usage' under it
- versions
