### ISSUE TITLE
Add basic support for OP_RETURN

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#302]
- Add a new `op-return` parameter which will add `opreturn=[hex of their string]`
- It needs to be converted to hex so we'll need to do that before adding it into the URI + QR code

Probably helpful: https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/cashtab/src/opreturn/index.js

We get to decide how we want the OP_RETURN to be decoded.

**Comment by Klakurka** [comment]
Just allowing them to enter it as JSON might be the play but we can talk about it

Either way, we're limited to 223 bytes or less.

**Comment by Klakurka** [comment]
We'll need some sort of error handling if they enter something too long.

**Comment by Klakurka** [comment]
Another format suggestion:

- allow entering a string that contains spaces and colons. Split on spaces first.
- split on colons, where the left side is the key and the right side is the value. If no colon exists then it's just a value.

**Comment by Klakurka** [comment]
Some examples using the above formatting suggestion:

Code: `opreturn="ecash:ABC123XYZ INVOICE#|778 Notes|'I really like eCash!!!!'"`

What would be entered into the database:

1. `ecash:ABC123XYZ`
2. `INVOICE#` = `778`
3. `Notes` = `I really like eCash!!!!`

**Comment by Klakurka** [comment]
https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/standards/bip21-ecash-additions.md

**Comment by ethanmackie** [comment]
> Some examples using the above formatting suggestion:
> 
> Code: `opreturn="ecash:ABC123XYZ INVOICE#|778 Notes|'I really like eCash!!!!'"`
> 
> What would be entered into the database:
> 
> 1. `ecash:ABC123XYZ` (key would be `null`)
> 2. `INVOICE#` = `778`
> 3. `Notes` = `I really like eCash!!!!`

FYI - the space for notes may be much less than 223 bytes.

i.e. breaking down the OP_RETURN output script:

- 1 byte of [opreturn prefix] + 
- 4 bytes of [protocol identifier] (see [opreturn prefix std](https://github.com/Bitcoin-ABC/bitcoin-abc/blob/master/doc/standards/op_return-prefix-guideline.md))+ 
- 32 bytes of [ecash address] + 
- 14 bytes of [invoice #] (assuming capped at 1M)+ 
- 172 bytes of [Notes] (or approx 86 characters)

Main size variable is the max invoice byte length, which will directly eat into the available bytes for Notes. The others in the script are all constant sizes.

For reference, this is a breakdown of a cashtab message OP_RETURN hex:

![image](https://github.com/PayButton/paybutton/assets/87533556/009a9da1-a7ab-4e13-845d-1b300923a8ef)

**Comment by Klakurka** [comment]
@ethanmackie basically in my above example, everything inside the quotes is the "message". It's up to the website owner what they want to put in there - but I was also trying to explain how we might parse it on the server.

The idea is that we at the very minimum want to support arbitrary values without keys, but it would also be helpful to be able to support creating custom key/value pair too to give them flexibility.

**Comment by Klakurka** [comment]
Still need to pass the OP_RETURN message back to the client so it can be checked against what's expected, allowing for `random-satoshis` to be deprecated.
