### ISSUE TITLE
PayButton fail to load in Firefox 75.0 

### ISSUE THREAD

**Issue by aconsuegra2014** [PayButton/paybutton#38]
The next code fail to load in firefox 75.0, ubuntu 16.04
```
<!DOCTYPE html>
<html>
<head>
<title></title>
<meta charset="utf-8">
<script src="https://unpkg.com/@paybutton/paybutton@1.0.2/dist/paybutton.js"></script>

</head>
<body>
<div class="paybutton" to="qpt2mwxslt5rvkrrv4drme5g8nlap0ahuqr77e0t52"></div>

</body>
</html>
```

The browser console show

SyntaxError: invalid identity escape in regular expression

**Comment by Klakurka** [comment]
Can you try updating to the latest FF and see if it's still an issue?

We've tested in Ubuntu, Arch, Win 7, and Win 10 on FireFox 81.0.X and it runs without any issues.

**Comment by aconsuegra2014** [comment]
Yes, in firefox 81.0.X works well but not in firefox 75.0

**Comment by Klakurka** [comment]
We might be able to ignore this one unless it comes up again in a later version since most people should be on v81+.

We'll leave it open for now. Thanks for the heads up.

**Comment by Klakurka** [comment]
All newer version of FF seem to work fine so I'm going to close this one.
