### ISSUE TITLE
When will BCH be added back?

### ISSUE THREAD

**Issue by minisat0shi** [PayButton/paybutton#443]

**Comment by Klakurka** [comment]
If there's a specific bug you're seeing, you can let us know but BCH has been supported since day 1. The server was updated to use BCHC as part of https://github.com/PayButton/paybutton-server/releases/tag/3.0.0 back in August.

**Comment by minisat0shi** [comment]
Thanks -- unclear based on the readme and website. Only mentions XEC. Thank you for the clarification.

**Comment by minisat0shi** [comment]
> If there's a specific bug you're seeing, you can let us know but BCH has been supported since day 1. The server was updated to use BCHC as part of https://github.com/PayButton/paybutton-server/releases/tag/3.0.0 back in August.

Looking again, where is BCH supported on the website? Only XEC is listed even to create a button. The docs mention BCH as an option but the paybutton website does not have it as an option. Thanks

**Comment by minisat0shi** [comment]
@Klakurka bumping this

**Comment by Klakurka** [comment]
- ![image](https://github.com/user-attachments/assets/9119a7f6-f0bc-43f4-8875-8ffd8afc39d0)
- ![image](https://github.com/user-attachments/assets/72444926-0e10-44f3-bf1c-93931b83b872)

It's all auto-detecting based on the address format used.
