### ISSUE TITLE
Error when trying to install React component

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#72]
Steps to reproduce

- install new nextjs directory
- cd
- npm i @paybutton/react

**Comment by paOol** [comment]
more context,

``` 
 "peerDependencies": {
    "react": "^16.13.1",
    "react-dom": "^16.13.1"
  },
```
in package.json results in an error when trying to install paybutton on react 17 and higher.

also i think the rollup bundler change to `umd` fixed the initial issue.

**Comment by vorg-code** [comment]
I have just executed `npm i @paybutton/react` on a fresh next js project and it installed without issues:
```
"dependencies": {
    "@paybutton/react": "^1.2.2"
  }
```
