### ISSUE TITLE
Parameter for allowing individuals to edit the amount

### ISSUE THREAD

**Issue by Klakurka** [PayButton/paybutton#86]
A small edit/pencil button would be visible somewhere.

If amount is null/0: 
![image](https://user-images.githubusercontent.com/4713204/109568314-98fa6b80-7a9b-11eb-8d38-941d3347c1ee.png)

If amount is >0: 
![image](https://user-images.githubusercontent.com/4713204/109568276-86803200-7a9b-11eb-87d9-f909cd8cfd37.png)

**Comment by Klakurka** [comment]
I actually don't mind this.

Feedback:

 - We should add an error message for negative numbers. Text should be `Amount should be positive`.
 - Pencil can be maybe reduced in size from 30 -> 20.
 - Add input character limit to input of maybe 12.
 - If input is empty, set the value to 0, which would also trigger the new `Amount should be positive` error.
 - Error message location could be moved from the bottom to the top bar section rather than it displaying this: 
![image](https://user-images.githubusercontent.com/4713204/112397477-653beb80-8cbf-11eb-8322-a65067bdb562.png)

**Comment by paOol** [comment]
one note, 
I think the default behavior (0 amount) should show `Send any amount of BCH` and not an error state.

**Comment by Klakurka** [comment]
Yep, you're right.
